psiapp/cves/forms.py
import re

from flask_wtf import FlaskForm
from wtforms.fields import StringField, SubmitField
from wtforms.validators import DataRequired, Length, Regexp


class CVESearchForm(FlaskForm):
    cve_id = StringField(
        label="CVE ID",
        validators=[
            DataRequired(),
            Length(
                min=13,
                max=15,
                message="A CVE ID is %(min)d to %(max)d characters long!",
            ),
            Regexp(
                regex=r"^CVE-\d{4}-\d{3,5}$",
                flags=re.IGNORECASE,
                message="A CVE ID must be in the format of CVE-YYYY-NNNN!",
            ),
        ],
        render_kw={"placeholder": "Enter a CVE ID"},
    )
    search = SubmitField()

psiapp/cves/__init__.py
from flask import Blueprint

bp = Blueprint("cves", __name__, url_prefix="/cve", template_folder="templates")

from psiapp.cves import views

psiapp/cves/views.py
import requests
from flask import flash, redirect, render_template, request, session, url_for
from markupsafe import escape

from psiapp import limiter
from psiapp.cves import bp
from psiapp.cves.forms import CVESearchForm
from psiapp.utils import fetch_data


# CVE Search Form Page
@bp.route("/", methods=["GET", "POST"])
@limiter.exempt
def cve(title="CVE ID"):
    form = CVESearchForm()
    if form.validate_on_submit():
        cve_id = escape(form.cve_id.data.strip().upper())
        return redirect(url_for(".result", cve_id=cve_id))
    return render_template("cve/form.html", title=title, form=form)


# CVE Search Results Page
@bp.get("/result")
def result():
    if not request.args.get("cve_id", None, type=str):
        flash("A Cisco CVE ID is required!", "danger")
        return redirect(url_for(".cve"))
    cve_id = escape(request.args.get("cve_id").strip().upper())
    try:
        res = fetch_data(
            uri=f"cve/{cve_id}?productNames=true",
            access_token=session.get("access_token"),
        )
    except requests.exceptions.ConnectionError as e:
        flash("Connection Error! Failed to establish a connection", "danger")
        return redirect(url_for(".cve"))
    except requests.exceptions.HTTPError as e:
        if e.response.status_code == 403:
            flash(
                "Session has expired! You are redirected to the Home page to refresh your session",
                "info",
            )
            return redirect(url_for("main.index"))
        if e.response.status_code == 404:
            flash(e.response.json().get("errorMessage"), "danger")
            return redirect(url_for(".cve"))
        if e.response.status_code == 406:
            flash(f"Unacceptable format of CVE ID {cve_id}!", "danger")
            return redirect(url_for(".cve"))
        flash(str(e), "danger")
        return redirect(url_for(".cve"))
    else:
        flash(f"Search result for {cve_id}", "success")
        advisories = res.json().get("advisories")
        return render_template("cve/result.html", title=cve_id, cve=advisories)

psiapp/cves/templates/cve/form.html
{% extends "layout.html" %}

{% block content %}
<form method="post" enctype="application/x-www-form-urlencoded" role="form" onsubmit="submitSearchForm();" novalidate>
    {{ form.csrf_token }}
    <div class="motion-fade-in motion-delay--250 motion-speed--medium">
        <h2 class="h2 text-center text-size-48 base-margin-top base-margin-bottom">{{ title }}</h2>
        <div class="form-group qtr-margin-bottom {% if form.cve_id.errors %}form-group--error{% endif %}">
            <div class="form-group__text">
                {{ form.cve_id }}
            </div>
            {{ with_errors(form.cve_id) }}
        </div>
        <div class="text-center base-margin-bottom base-margin-top">
            {{ search_btn(form.search) }}
        </div>
        <p>Examples: <span class="label label--tertiary label--small">CVE-2022-20906</span> or <span
                class="label label--tertiary label--small">CVE-2022-20874</span></p>
    </div>
</form>
{% endblock content %}

{% block javascript %}
<script src="{{ url_for('static', filename='js/app.min.js') }}"></script>
{% endblock javascript %}

psiapp/cves/templates/cve/result.html
{% extends "layout.html" %}

{%- block content -%}
<!-- Breadcrumb -->
{{ breadcrumb('.cve', "CVE", title) }}

<hr />

{%- for advisory in cve -%}
<div class="row">
    <div class="col-md-8 col-12">
        <div class="row">
            <div class="col-12">
                <h2 class="h2">{{ advisory.advisoryTitle }}</h2>
            </div>
            <!-- Score -->
            {% include 'includes/score.html' %}
            <!-- Machine Readable Formats -->
            {% include 'includes/mrf.html' %}
        </div>
        <div class="base-margin-bottom">
            <h3 class="h3">Summary</h3>
            <div class="summary">{{ advisory.summary|safe }}</div>

            <hr />

            <h3 class="h3">Status</h3>
            <div class="responsive-table">
                <table class="table table--bordered table--bordered-inner">
                    <thead>
                        <tr>
                            <th scope="col">Version</th>
                            <th scope="col">First Published</th>
                            <th scope="col">Last Updated</th>
                            <th scope="col">Current Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{{ advisory.version }}</td>
                            {%- if advisory.firstPublished == advisory.lastUpdated -%}
                            <td>{{ advisory.firstPublished|fromtimestamp }}</td>
                            <td>Never</td>
                            {%- else -%}
                            <td>{{ advisory.firstPublished|fromtimestamp }}</td>
                            <td>{{ advisory.lastUpdated|fromtimestamp }}</td>
                            {%- endif -%}
                            <td>{{ advisory.status }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="col-md-4 col-sm-12">
        {%- if advisory.productNames[0] != "NA" -%}
        <div class="base-margin-bottom">
            <h3 class="h3 relative">
                Affected Product{%- if advisory.productNames|length > 1 -%}s{%- endif %}
                {% if advisory.productNames|length > 10 %}
                <span class="badge badge--secondary">{{ "{:,}".format(advisory.productNames|length) }}</span>
                {% endif %}
            </h3>
            <ul>
                {%- for platform in advisory.productNames -%}
                <li class="productName {% if advisory.productNames|length != 1 %}hide{% endif %}">{{ platform }}</li>
                {%- endfor -%}
            </ul>
            {% if advisory.productNames|length > 10 %}
            <button class="btn btn--ghost btn--small half-margin-top hide" id="loadMore">Load more <span
                    class="icon-more"></span></button>
            <span id="or">OR</span>
            <button class="btn btn--ghost btn--small half-margin-top hide" id="loadAll">Load all</button>
            {% endif %}
        </div>
        {% endif %}

        {% if advisory.cves|length %}
        <div class="base-margin-bottom">
            <h3 class="h3 related-cve">
                Related CVE{%- if advisory.cves|length > 1 -%}s{%- endif -%}
            </h3>
            <ul>
                {%- for cve in advisory.cves -%}
                <li class="cve-item">
                    <a class="qtr-padding-right {% if cve == request.args.get('cve_id') %}text-gray-700{% endif %}"
                        href="{{url_for('cves.result', cve_id=cve)}}">{{ cve }}</a>
                    <a class="label label--primary label--tiny text-white" href="//www.cve.org/CVERecord?id={{cve}}"
                        target="_blank" rel="noopener noreferrer" title="{{ cve }} on CVE">CVE</a>
                    <a class="label label--secondary label--tiny text-white" href="//nvd.nist.gov/vuln/detail/{{cve}}"
                        target="_blank" rel="noopener noreferrer" title="{{ cve }} on NVD">NVD</a>
                    <a class="label label--light label--tiny" href="//vulmon.com/vulnerabilitydetails?qid={{ cve }}"
                        target="_blank" rel="noopener noreferrer" title="{{ cve }} on Vulmon">Vulmon</a>
                </li>
                {%- endfor -%}
            </ul>
        </div>
        {% endif %}
        {%- if advisory.cwe and advisory.cwe[0] not in ["NA", "CWE"] -%}
        <div class="base-margin-bottom">
            <h3 class="h3 related-cwe">
                Related CWE{%- if advisory.cwe|length > 1 -%}s{%- endif -%}
            </h3>
            <ul>
                {%- for cwe in advisory.cwe -%}
                <li class="cwe-item">
                    <a href="//cwe.mitre.org/data/definitions/{{ cwe.split('-')[1] }}.html" target="_blank"
                        rel="noopener noreferrer" title="{{ cwe }}">{{ cwe }} <span
                            class="icon-jump-out icon-size-12 qtr-padding-left"></span></a>
                </li>
                {%- endfor -%}
            </ul>
        </div>
        {%- endif -%}

        {%- if advisory.bugIDs[0] != "NA" -%}
        <h3 class="h3 related-bugs">Related Bug ID{%- if advisory.bugIDs|length > 1 -%}s{%- endif -%}</h3>
        <ul>
            {%- for bug_id in advisory.bugIDs -%}
            <li class="bug-item">
                <a class="qtr-padding-right" href="{{ url_for('bugs.result', bug_id=bug_id) }}"
                    title="{{ bug_id }}">{{ bug_id }}</a>
                <a class="label label--dark label--tiny text-white"
                    href="//bst.cloudapps.cisco.com/bugsearch/bug/{{ bug_id }}" target="_blank"
                    rel="noopener noreferrer" title="{{ bug_id }} on Cisco Bug Search Tool">BST <span
                        class="icon-jump-out icon-size-10 qtr-padding-left"></span></a>
            </li>
            {%- endfor -%}
        </ul>
        {%- endif -%}
    </div>
</div>
{%- endfor -%}

<hr />

{% include "includes/legal_disclaimer.html" %}
{%- endblock content -%}

{% block javascript %}
<script src="{{ url_for('static', filename='js/loadMore.min.js') }}"></script>
{% endblock javascript %}