psiapp/bugs/forms.py
import re

from flask_wtf import FlaskForm
from wtforms.fields import StringField, SubmitField
from wtforms.validators import DataRequired, Length, Regexp


class BugSearchForm(FlaskForm):
    bug_id = StringField(
        label="Cisco Bug ID",
        validators=[
            DataRequired(),
            Length(
                min=9,
                max=10,
                message="Cisco Bug ID is %(min)d to %(max)d characters long!",
            ),
            Regexp(
                regex=r"^.*$",
                flags=re.IGNORECASE,
                message="Cisco Bug ID uses a pattern of CSCxxNNNN, where xx are any two letter (a-z) and NNNN are any four numbers (0-9)",
            ),
        ],
        render_kw={"placeholder": "Enter a Cisco Bug ID"},
    )
    search = SubmitField()

psiapp/bugs/__init__.py
from flask import Blueprint

bp = Blueprint("bugs", __name__, template_folder="templates")

from psiapp.bugs import views

psiapp/bugs/views.py
import requests
from flask import flash, redirect, render_template, request, session, url_for
from markupsafe import escape

from psiapp import limiter
from psiapp.bugs import bp
from psiapp.bugs.forms import BugSearchForm
from psiapp.utils import fetch_data


# Cisco Bug ID Search Form Page
@bp.route("/", methods=["GET", "POST"])
@limiter.exempt
def bug(title="Bug ID"):
    form = BugSearchForm()
    if form.validate_on_submit():
        bug_id = form.bug_id.data.strip()
        return redirect(url_for(".result", bug_id=bug_id))
    return render_template("bug/form.html", title=title, form=form)


# Cisco Bug ID Result Page
@bp.get("/result")
def result():
    if not request.args.get("bug_id", None, type=str):
        flash("A Cisco bug ID is required!", "danger")
        return redirect(url_for(".bug"))
    bug_id = escape(request.args.get("bug_id").strip())
    try:
        res = fetch_data(
            uri=f"bugid/{bug_id}?productNames=true",
            access_token=session.get("access_token"),
        )
    except requests.exceptions.ConnectionError as e:
        flash("Connection Error! Failed to establish a connection", "danger")
        return redirect(url_for(".bug"))
    except requests.exceptions.HTTPError as e:
        if e.response.status_code == 403:
            flash(
                "Session has expired! You are redirected to the Home page to refresh your session",
                "info",
            )
            return redirect(url_for("main.index"))
        if e.response.status_code == 404:
            flash(e.response.json().get("errorMessage"), "danger")
            return redirect(url_for(".bug"))
        if e.response.status_code == 503:
            flash(
                "The service is currently unavailable from Cisco! Please try again later",
                "danger",
            )
            return redirect(url_for(".bug"))
        flash(str(e), "danger")
        return redirect(url_for(".bug"))
    else:
        flash(f"Search result for {bug_id}", "success")
        advisories = res.json().get("advisories")
        return render_template("bug/result.html", title=bug_id, bug=advisories)

psiapp/bugs/templates/bug/form.html
{% extends "layout.html" %}

{% block content %}
<form method="post" enctype="application/x-www-form-urlencoded" role="form" onsubmit="submitSearchForm();" novalidate>
    {{ form.csrf_token }}
    <div class="motion-fade-in motion-delay--250 motion-speed--medium">
        <h2 class="h2 text-center text-size-48 base-margin-top base-margin-bottom">{{ title }}</h2>
        <div class="form-group qtr-margin-bottom {% if form.bug_id.errors %}form-group--error{% endif %}">
            <div class="form-group__text">
                {{ form.bug_id }}
            </div>
            {{ with_errors(form.bug_id) }}
        </div>
        <div class="text-center base-margin-bottom base-margin-top">
            {{ search_btn(form.search) }}
        </div>
        <p>Examples: <span class="label label--tertiary label--small">CSCwb75093</span> or
            <span class="label label--tertiary label--small">CSCwc62415</span>
        </p>
    </div>
</form>
<div class="fixed-bottom opacity-90">
    <p class="bg-tertiary text-xsmall text-white base-padding">Cisco does not provide advisories for
        third-party software products, even if it has a Cisco Bug ID on Bug Search Tools.</p>
</div>
{% endblock content %}

{% block javascript %}
<script src="{{ url_for('static', filename='js/app.min.js') }}"></script>
{% endblock javascript %}

psiapp/bugs/templates/bug/result.html
{% extends "layout.html" %}

{%- block content -%}
<!-- Breadcrumb -->
{{ breadcrumb('.bug', 'Bug', title) }}

<hr />

{%- for advisory in bug -%}
<div class="row">
    <div class="col-md-8 col-12">
        <div class="row">
            <div class="col-12">
                <h2 class="h2">{{ advisory.advisoryTitle }}</h2>
            </div>
            <!-- Score -->
            {% include 'includes/score.html' %}
            <!-- Machine Readable Formats -->
            {% include 'includes/mrf.html' %}
        </div>
        <div class="base-margin-bottom">
            <h3 class="h3">Summary</h3>
            <div class="summary">{{ advisory.summary|safe }}</div>

            <hr />

            <h3 class="h3">Status</h3>
            <div class="responsive-table">
                <table class="table table--bordered table--bordered-inner">
                    <thead>
                        <tr>
                            <th scope="col">Version</th>
                            <th scope="col">First Published</th>
                            <th scope="col">Last Updated</th>
                            <th scope="col">Current Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{{ advisory.version }}</td>
                            {%- if advisory.firstPublished == advisory.lastUpdated -%}
                            <td>{{ advisory.firstPublished|fromtimestamp }}</td>
                            <td>Never</td>
                            {%- else -%}
                            <td>{{ advisory.firstPublished|fromtimestamp }}</td>
                            <td>{{ advisory.lastUpdated|fromtimestamp }}</td>
                            {%- endif -%}
                            <td>{{ advisory.status }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="col-md-4 col-sm-12">
        {%- if advisory.productNames[0] != "NA" -%}
        <div class="base-margin-bottom">
            <h3 class="h3 relative">
                Affected Product{%- if advisory.productNames|length > 1 -%}s{%- endif %}
                {% if advisory.productNames|length > 10 %}
                <span class="badge badge--secondary">{{ "{:,}".format(advisory.productNames|length) }}</span>
                {% endif %}
            </h3>
            <ul>
                {%- for platform in advisory.productNames -%}
                <li class="productName {% if advisory.productNames|length != 1 %}hide{% endif %}">{{ platform }}</li>
                {%- endfor -%}
            </ul>
            {% if advisory.productNames|length > 10 %}
            <button class="btn btn--ghost btn--small half-margin-top hide" id="loadMore">Load more <span
                    class="icon-more"></span></button>
            <span id="or">OR</span>
            <button class="btn btn--ghost btn--small half-margin-top hide" id="loadAll">Load all</button>
            {% endif %}
        </div>
        {% endif %}

        <div class="base-margin-bottom">
            <h3 class="related-cve">
                Related CVE{%- if advisory.cves|length > 1 -%}s{%- endif -%}
            </h3>
            <ul>
                {%- for cve_id in advisory.cves -%}
                <li class="cve-item">
                    <a class="qtr-padding-right" href="{{ url_for('cves.result', cve_id=cve_id) }}">{{ cve_id }}</a>
                    <a class="label label--primary label--tiny text-white"
                        href="//www.cve.org/CVERecord?id={{ cve_id }}" target="_blank" rel="noopener noreferrer"
                        title="{{cve_id}} on CVE">CVE</a>
                    <a class="label label--secondary label--tiny text-white"
                        href="//nvd.nist.gov/vuln/detail/{{ cve_id }}" target="_blank" rel="noopener noreferrer"
                        title="{{cve_id}} on NVD">NVD</a>
                    <a class="label label--light label--tiny" href="//vulmon.com/vulnerabilitydetails?qid={{ cve_id }}"
                        target="_blank" rel="noopener noreferrer" title="{{ cve_id }} on Vulmon">Vulmon</a>
                </li>
                {%- endfor -%}
            </ul>
        </div>

        {%- if advisory.cwe and advisory.cwe[0] not in ["NA", "CWE"] -%}
        <div class="base-margin-bottom">
            <h3 class="h3 related-cwe">
                Related CWE{%- if advisory.cwe|length > 1 -%}s{%- endif -%}
            </h3>
            <ul>
                {%- for cwe in advisory.cwe -%}
                <li class="cwe-item">
                    <a href="//cwe.mitre.org/data/definitions/{{ cwe.split('-')[1] }}.html" target="_blank"
                        rel="noopener noreferrer" title="{{ cwe }}">{{ cwe }} <span
                            class="icon-jump-out icon-size-12 qtr-padding-left"></span></a>
                </li>
                {%- endfor -%}
            </ul>
        </div>
        {%- endif -%}

        {%- if advisory.bugIDs[0] != "NA" -%}
        <h3 class="h3 related-bugs">Related Bug ID{%- if advisory.bugIDs|length > 1 -%}s{%- endif -%}</h3>
        <ul>
            {%- for bug_id in advisory.bugIDs -%}
            <li class="bug-item">
                <a class="qtr-padding-right {% if bug_id == request.args.get('bug_id') %}text-gray-700{% endif %}"
                    href="{{ url_for('bugs.result', bug_id=bug_id) }}" title="{{ bug_id }}">{{ bug_id }}</a>
                <a class="label label--dark label--tiny text-white"
                    href="//bst.cloudapps.cisco.com/bugsearch/bug/{{ bug_id }}" target="_blank"
                    rel="noopener noreferrer" title="{{ bug_id }} on Cisco Bug Search Tool">BST <span
                        class="icon-jump-out icon-size-10 qtr-padding-left"></span></a>
            </li>
            {%- endfor -%}
        </ul>
        {%- endif -%}
    </div>
</div>
{%- endfor -%}

<hr />

{% include "includes/legal_disclaimer.html" %}
{%- endblock content -%}

{% block javascript %}
<script src="{{ url_for('static', filename='js/loadMore.min.js') }}"></script>
{% endblock javascript %}